version: "2"
services:
  frontend:
    depends_on:
      - api
    image: ${mf_frontend_image}
    environment:
      APPLICATION_NAME: frontend
    ports:
      - "8888:8888"
    env_file:
      - ./../.envrc

  workflows:
    depends_on:
      - postgres
      - eventstore
    image: ${mf_workflows_image}
    env_file:
      - ./../.envrc
    environment:
      APPLICATION_NAME: workflows

  projections:
    depends_on:
      - data
      - postgres
      - eventstore
    image: ${mf_projections_image}
    env_file:
      - ./../.envrc
    environment:
      APPLICATION_NAME: projections

  api:
    image: ${mf_api_image}
    ports:
      - 3666:3000
    env_file:
      - ./../.envrc
    environment:
      APPLICATION_NAME: api

  data:
    depends_on:
      - postgres
    image: ${mf_data_image}
    env_file:
      - ./../.envrc
    environment:
      APPLICATION_NAME: data

  postgres:
    image: postgres
    ports:
      - 5400:5432
    env_file:
      - ./../.envrc

  eventstore:
    image: eventstore/eventstore
    ports:
      - 2113:2113
      - 1113:1113
    environment:
      - ext-http-prefixes=http://*:2113/
      - ext-ip="0.0.0.0"
      - log=/data/logs
      - stats-period-sec=3000000
