version: "2"
services:
  frontend:
    depends_on:
      - api
    command: npm run start2 #top -b #
    image: ${mf_frontend_image}
    restart: on-failure
    environment:
      APPLICATION_NAME: frontend
    ports:
      - "80:8888"
    env_file:
      - ./.env

  workflows:
    depends_on:
      - postgres
      - eventstore
    command: npm run startRemoteContainer #top -b #
    image: ${mf_workflows_image}
    restart: on-failure
    env_file:
      - ./.env
    environment:
      APPLICATION_NAME: workflows

  projections:
    depends_on:
      - data
      - postgres
      - eventstore
    command: npm run startRemoteContainer #top -b #
    image: ${mf_projections_image}
    restart: on-failure
    env_file:
      - ./.env
    environment:
      APPLICATION_NAME: projections

  api:
    image: ${mf_api_image}
    restart: on-failure
    command: npm run startRemoteContainer #top -b #
    ports:
      - 3666:3000
    env_file:
      - ./.env
    environment:
      APPLICATION_NAME: api

  data:
    depends_on:
      - postgres
    command: npm start
    image: ${mf_data_image}
    env_file:
      - ./.env
    environment:
      TZ: "America/Chicago"
      APPLICATION_NAME: data

  postgres:
    image: postgres
    ports:
      - 5400:5432
    env_file:
      - ./.env

  eventstore:
    image: eventstore/eventstore
    ports:
      - 2113:2113
      - 1113:1113
    environment:
      - ext-http-prefixes=http://*:2113/
      - ext-ip="0.0.0.0"
      - log=/data/logs
      - stats-period-sec=3000000

